### PR TITLE
feat(mesh/story): add story page api-data renderer part3

### PR DESCRIPTION
**Pull request by caesarWHLee**
# Features
Add embed code block and adjust story page layout.

Since Readr's story use a lot of full screen embed code and the full screen css is maintained inside the embed code itself.
It is hard for the renderer to detect which should embed content take the full screen size and then adjust the block (wrapper) css to be horizontally aligned. The solution is to turn Mesh story page's article block into a horizontal aligned style so the embed code can extend to the full screen correctly just like it does in Readr's story page.

For now the new design for desktop navbar and desktop aside are not yet being made. So the temp version is here to make the embed code and the following task for story page not be blocked.

Related PR: #799, #807

## Added block
- embed block (check id `1241502` or other readr posts to see how embed code renders)

## Known Issue
- The navbar will cover the article content in screen width 768px and 960px.   
- Readr story with id `1241503 ` contains broken embed code (due to the combination of Readr's leading embed code)

### CODE REVIEW

**Comment by caesarWHLee** [comment]
@tyc67 @LinHeMa 也可以看一下 story layout, page 的改動，目前會把文章區塊置中在頁面的正中間，讓滿版的 embed code 可以正常的位移到畫面最左邊填滿整個螢幕的寬，這個改對意味著 story 頁會和其他的頁面的 layout 脫節

**Review by erase2004 — COMMENTED** [review]
Snipaste_2024-07-31_19-51-21
Snipaste_2024-07-31_19-48-03
這個區塊的 embeded code 會覆蓋 header 或 navbar，是預期的行為？或者已知問題？

**Comment by caesarWHLee** [comment]
> 796a266

這個是 bug， embed code 會依照 caption 是否帶 `reporter-scroll-video` 來決定設定 `z-index` 與否，感謝抓蟲，已修正在 [796a266](https://github.com/readr-media/Sachiel/pull/811/commits/796a2660ca0ba280eda97c610328a61348a162d9)

**Comment by caesarWHLee** [comment]
> Snipaste_2024-07-31_19-51-21 Snipaste_2024-07-31_19-48-03 這個區塊的 embeded code 會覆蓋 header 或 navbar，是預期的行為？或者已知問題？

這個是 bug， embed code 會依照 caption 是否帶 `reporter-scroll-video` 來決定設定 `z-index` 與否，感謝抓蟲，已修正在 [796a266](https://github.com/readr-media/Sachiel/pull/811/commits/796a2660ca0ba280eda97c610328a61348a162d9)

**Review by erase2004 — APPROVED** [review]
LGTM 👏

**Pull request merged**
